# Generated by Django 2.2.8 on 2019-12-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191210_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('CULTURE', 'Culture'), ('ENTERTAINMENT', 'Entertainment'), ('None', 'None')], default=('None', 'None'), max_length=50),
        ),
    ]
