# Generated by Django 2.2.8 on 2019-12-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('TECHNOLOGY', 'Technology'), ('CULTURE', 'Culture'), ('ENTERTAINMENT', 'Entertainment'), ('MUSIC', 'Music'), ('DANCE', 'Dance'), ('NONE', 'None')], default=('NONE', 'None'), max_length=50),
        ),
    ]
