# Generated by Django 2.2.8 on 2019-12-18 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_images'),
        ('blog', '0004_post_topic'),
    ]

    operations = [
    ]
