# Generated by Django 3.0 on 2019-12-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_reply'),
        ('blog', '0005_merge_20191218_1325'),
    ]

    operations = [
    ]
