# Generated by Django 2.2.8 on 2019-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191209_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank='True', default='default.jpg', null='True', upload_to='post_images'),
        ),
    ]
