# Generated by Django 3.0 on 2019-12-24 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_merge_20191219_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank='True', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
