# Generated by Django 2.2.8 on 2019-12-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_merge_20191219_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isQuestion',
            field=models.BooleanField(default=False),
        ),
    ]
