# Generated by Django 2.2.8 on 2019-12-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191209_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank='True', null='True', upload_to='post_images'),
        ),
    ]
