# Generated by Django 3.0 on 2019-12-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_answer'),
        ('blog', '0007_post_like'),
    ]

    operations = [
    ]
