# Generated by Django 2.2.8 on 2019-12-29 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank='True', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
