# Generated by Django 2.2.8 on 2019-12-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_like'),
        ('blog', '0008_answer'),
    ]

    operations = [
    ]
