# Generated by Django 3.0 on 2019-12-29 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_merge_20191229_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='save',
            field=models.ManyToManyField(blank='True', related_name='saves', to=settings.AUTH_USER_MODEL),
        ),
    ]
