# Generated by Django 2.2.8 on 2019-12-31 17:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_merge_20191231_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed_users',
            field=models.ManyToManyField(related_name='viewed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
