# Generated by Django 3.0 on 2020-01-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_viewed_users'),
        ('blog', '0010_post_save'),
    ]

    operations = [
    ]
