# Generated by Django 2.2.8 on 2023-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='recruit.Student'),
        ),
    ]
