# Generated by Django 2.2.8 on 2023-06-21 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_auto_20230621_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='INCOMPLETE', max_length=16)),
                ('start_date', models.DateField()),
                ('update_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruit.Student')),
            ],
        ),
    ]
