# Generated by Django 2.2.8 on 2023-06-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('url', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='assessment_graded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='assessment_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='received_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='schedule_interview',
            field=models.BooleanField(default=False),
        ),
    ]
