# Generated by Django 2.2.8 on 2023-06-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_auto_20230621_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, to='recruit.Position'),
        ),
    ]
