# Generated by Django 2.2.8 on 2023-06-21 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_event_positions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Recruit',
        ),
    ]
